import type { Metadata } from "next";
import { Baloo_2, Fredoka } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import TopMarquee from "./components/Marquee";

const baloo = Baloo_2({
    subsets: ["latin"],
    variable: "--font-baloo",
    display: "swap",
});

const fredoka = Fredoka({
    subsets: ["latin"],
    variable: "--font-fredoka",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${baloo.variable} ${fredoka.variable} font-sans antialiased m-0 p-0 overflow-x-hidden`}
            >
                <TopMarquee />
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
